server:
  port: 8081

spring:
  application:
    name: producer-server
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${base.db.mysql.username}
    password: ${base.db.mysql.password}
    url: ${base.db.mysql.url}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
      use-unfair-lock: true
      pool-prepared-statements: false
      validation-query: SELECT 1 FROM dual
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filters: stat,wall,slf4j
  zipkin:
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 10000
        min-idle: 8
      shutdown-timeout: 100

jasypt:
  encryptor:
    bean: stringEncryptorUtil
#    password: guzx970712
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#    启动手动添加password  java -jar -Djasypt.encryptor.password=guzx970712 XXX.jar

eureka:
  client:
    health-check:
      enabled: true
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    status-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/manage/
    # 心跳间隔
    lease-renewal-interval-in-seconds: 30

feign:
  client:
    default-config: default
    config:
      default:
        readTimeout: 6000
        connectTimeout: 6000
  circuitbreaker:
    enabled: true


# 降级处理是否可以由全局异常处理与超时处理组成即可，不用circuitBreaker相关配置
hystrix:
  command:
    default:
#      降级配置
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
#      熔断配置
      metrics:
        rollingStats:
#          统计时间窗口
          timeInMilliseconds: 10000
      circuitBreaker:
        enabled: true
        # 统计时间窗内请求次数
        requestVolumeThreshold: 10
        # 熔断时间
        sleepWindowInMilliseconds: 10000
        # 错误率
        errorThresholdPercentage: 50


