server:
  port: 8081

spring:
  application:
    name: producer-server
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${base.db.mysql.username}
    password: ${base.db.mysql.password}
    url: ${base.db.mysql.url}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
      use-unfair-lock: true
      pool-prepared-statements: false
      validation-query: SELECT 1 FROM dual
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filters: stat,wall,slf4j
  zipkin:
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 10000
        min-idle: 8
      shutdown-timeout: 100
    cluster:
      max-redirects: 5

jasypt:
  encryptor:
    bean: stringEncryptorUtil
#    password: guzx970712
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#    启动手动添加password  java -jar -Djasypt.encryptor.password=guzx970712 XXX.jar

eureka:
  client:
    health-check:
      enabled: true
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    status-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/manage/
    # 心跳间隔
    lease-renewal-interval-in-seconds: 30