server:
  port: 8090

spring:
  application:
    name: user-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${base.db.mysql.username}
    password: ${base.db.mysql.password}
    url: ${base.db.mysql.url}
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 10000
        min-idle: 8
      shutdown-timeout: 100
    cluster:
      max-redirects: 5

eureka:
  client:
    health-check:
      enabled: true
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    status-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/manage/
    lease-renewal-interval-in-seconds: 30
