server:
  port: 8090

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    host: local
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 5
        max-idle: 8
        max-wait: 1000
    timeout: 3000

#debug: true