server:
  port: 8090
#  servlet:
#    session:
#      timeout: 60

spring:
  application:
    name: user-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 5
        max-idle: 8
        max-wait: 1000
    timeout: 3000

eureka:
  client:
    health-check:
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8060/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    status-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/manage/
    lease-renewal-interval-in-seconds: 30

#debug: true