server:
  port: 8065

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 60
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 60

spring:
  application:
    name: gateway-server
  profiles:
    active: dev
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

