server:
  port: 8065

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    status-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/manage/
    lease-renewal-interval-in-seconds: 30

spring:
  application:
    name: gateway-server
  profiles:
    active: dev
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

