base:
  ip: 127.0.0.1
  mysql:
    url: jdbc:mysql://${base.ip}:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ENC(guzx)
    password: ENC(970712)
spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: ${base.mysql.username}
      password: ${base.mysql.password}
      url: ${base.mysql.url}
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
      use-unfair-lock: true
      pool-prepared-statements: false
      validation-query: SELECT 1 FROM dual
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filters: stat,wall,slf4j
management:
#  server:
#    port: 8081
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans
      path-mapping:
        health: healthcheck
      base-path: /manage
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    logfile:
      enabled: true