#base:
#  ip: 127.0.0.1
#  mysql:
#    url: jdbc:mysql://${base.ip}:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#    username: ENC(guzx)
#    password: ENC(970712)
#
#server:
#  port: 8081
#
#spring:
#  application:
#    name: demo-server
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${base.mysql.username}
#    password: ${base.mysql.password}
#    url: ${base.mysql.url}
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      username: ${base.mysql.username}
#      password: ${base.mysql.password}
#      url: ${base.mysql.url}
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 6000
#      use-unfair-lock: true
#      pool-prepared-statements: false
#      validation-query: SELECT 1 FROM dual
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      filters: stat,wall,slf4j
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    discovery-client-enabled: false
#  sleuth:
#    sampler:
#      probability: 1
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 10000
#    lettuce:
#      pool:
#        max-active: 20
#        max-idle: 8
#        max-wait: 10000
#        min-idle: 8
#      shutdown-timeout: 100
#
#jasypt:
#  encryptor:
##    自定义加密方法
#    bean: stringEncryptorUtil
##    启动手动添加password
##    java -jar -Djasypt.encryptor.password=guzx970712 XXX.jar
##    password: guzx970712
##    algorithm: PBEWithMD5AndDES
##    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#
#eureka:
#  client:
#    health-check:
#      enabled: true
#    service-url:
#      defaultZone: http://127.0.0.1:8060/eureka
#  instance:
#    instance-id: ${spring.application.name}
#    prefer-ip-address: true
#    status-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/manage/
#    # 心跳间隔
#    lease-renewal-interval-in-seconds: 30
#
#management:
#  #  server:
#  #    port: 8081
#  trace:
#    http:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: beans
#      path-mapping:
#        health: health-check
#      base-path: /manage
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      show-details: always
#    logfile:
#      enabled: true
#
test:
  name: dev

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 30MB
      file-size-threshold: 10MB

file:
  storage:
    path: D:\tempFile