server:
  port: 8080

spring:
  application:
    name: demo-server
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${base.mysql.username}
    password: ${base.mysql.password}
    url: ${base.mysql.url}
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
jasypt:
  encryptor:
#    自定义加密方法
    bean: stringEncryptorUtil
#    启动手动添加password
#    java -jar -Djasypt.encryptor.password=guzx970712 XXX.jar
#    password: guzx970712
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8060/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    status-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/manage/
    # 心跳间隔
    lease-renewal-interval-in-seconds: 30







