server:
  port: 8080
#  servlet:
#    context-path: /demo

base:
  ip: 127.0.0.1
  mysql:
    url: jdbc:mysql://${base.ip}:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: guzx
    password: 970712

spring:
  application:
    name: demo
#  profiles:
#    active: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${base.mysql.username}
#    password: ${base.mysql.password}
#    url: ${base.mysql.url}
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 6000
#      use-unfair-lock: true
#      pool-prepared-statements: false
#      validation-query: SELECT 1 FROM dual
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      filters: stat,slf4j,wall







