server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  application:
    name: demo
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${base.mysql.username}
    password: ${base.mysql.password}
    url: ${base.mysql.url}







