server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  application:
    name: demo
  profiles:
    active: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      username: ${base.mysql.username}
#      password: ${base.mysql.password}
#      url: ${base.mysql.url}
#      initial-size: 5
#      min-idle: 5
#      name: druid-datasource-01
#      max-active: 20
#      max-wait: 6000
#      use-unfair-lock: true
#      pool-prepared-statements: false
#      validation-query: SELECT 1 FROM dual
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      filters: stat,slf4j,wall






