server:
  port: 8060
spring:
  application:
    name: registry-server
  zipkin:
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  profiles:
    active: dev

eureka:
  instance:
    hostname: ${spring.application.name}
    # 等待下次心跳间隔(s)
    lease-expiration-duration-in-seconds: 90
  server:
    # 启用自我保护
    enable-self-preservation: true
    # 清理无效客户端
    eviction-interval-timer-in-ms: 600000
    peer-eureka-nodes-update-interval-ms: 100000
  client:
    register-with-eureka: false
    fetch-registry: false

