eureka:
  client:
    health-check:
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8060/eureka
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    status-page-url-path: http://${spring.cloud.client.ip-address}:${server.port}/manage/
    # 心跳间隔
    lease-renewal-interval-in-seconds: 30

base:
  ip: 127.0.0.1
  mysql:
    url: jdbc:mysql://${base.ip}:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ENC(root)
    password: ENC(123456)

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${base.mysql.username}
    password: ${base.mysql.password}
    url: ${base.mysql.url}

jasypt:
  encryptor:
#    自定义加密方法
    bean: stringEncryptorUtil
#    启动手动添加password
#    java -jar -Djasypt.encryptor.password=guzx970712 XXX.jar
#    password: guzx970712
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator

management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans
      path-mapping:
        health: health-check
      base-path: /manage
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    logfile:
      enabled: true